exports.websites = [
    {
        name: 'Get Waves',
        image: './public/assets/websiteimages/getwavesio.jpg',
        url: 'https://getwaves.io/',
        description: 'Create custom and unique SVG waves',
        keywords: ['waves', 'wave', 'svg', 'shape', 'shapes', 'svg shapes', 'svg waves'],
    },
    {
        name: 'uiverse',
        image: './public/assets/websiteimages/uiverseio.jpg',
        url: 'https://uiverse.io/',
        description: 'Choose from hundreds of design elements that are already coded for you! Just copy and paste!',
        keywords: ['button', 'buttons', 'checkbox', 'checkboxes', 'toggle', 'toggle switches', 'switches', 'cards', 'loaders', 'loading', 'loading icon', 'input', 'inputs'],
    },
    {
        name: 'css gradient',
        image: './public/assets/websiteimages/cssgradient.jpg',
        url: 'https://cssgradient.io/',
        description: 'Create CSS gradients visually, and then grab the code!',
        keywords: ['gradient', 'gradients', 'background', 'backgrounds', 'svg', 'svg background', 'background svg'],
    },
    {
        name: 'separator generator',
        image: './public/assets/websiteimages/sectionseparator.jpg',
        url: 'https://wweb.dev/resources/css-separator-generator/',
        description: 'Choose from 6 different styles of SVG backgrounds to help separate sections on your pages.',
        keywords: ['background', 'backgrounds', 'svg', 'svg background', 'background svg'],
    },
    {
        name: 'bgjar',
        image: './public/assets/websiteimages/uiverseio.jpg',
        url: 'https://bgjar.com/',
        description: 'Customize and generate SVG backgrounds.',
        keywords: ['background', 'backgrounds', 'svg', 'svg background', 'background svg'],
    },
    {
        name: 'animated background generator',
        image: './public/assets/websiteimages/wwebanimatedbg.jpg',
        url: 'https://wweb.dev/resources/animated-css-background-generator/',
        description: 'Fully customize and generate animated backgrounds with only HTML and CSS.',
        keywords: ['background', 'backgrounds', 'animated background', 'animated backgrounds'],
    },
    {
        name: 'svgbackgrounds',
        image: './public/assets/websiteimages/svgbackgrounds.jpg',
        url: 'https://www.svgbackgrounds.com/',
        description: 'Choose from a few complex and customizable SVG backgrounds.',
        keywords: ['background', 'backgrounds', 'svg', 'svg background', 'background svg'],
    },
    {
        name: 'waterpipe.js',
        image: './public/assets/websiteimages/waterpipe.jpg',
        url: 'http://dragdropsite.github.io/waterpipe.js/',
        description: 'Customize smoke-styled backgrounds',
        keywords: ['background', 'backgrounds', 'svg', 'svg background', 'background svg', 'smoke', 'smoky'],
    },
    {
        name: 'stripes generator',
        image: './public/assets/websiteimages/stripesgenerator.jpg',
        url: 'https://stripesgenerator.com/',
        description: 'Generate simple stripe backgrounds.',
        keywords: ['background', 'backgrounds', 'svg', 'svg background', 'background svg', 'stripes', 'stripe background', 'stripes background', 'stripe'],
    },
    {
        name: 'hero patterns',
        image: './public/assets/websiteimages/heropatterns.jpg',
        url: 'https://heropatterns.com/',
        description: 'Choose a simple, modern SVG background from over 40 options.',
        keywords: ['background', 'backgrounds', 'svg', 'svg background', 'background svg'],
    },
    {
        name: 'pattern generator',
        image: './public/assets/websiteimages/patterngenerator.jpg',
        url: 'https://doodad.dev/pattern-generator/',
        description: 'An incredibly complex, fully-customizable pattern generator.',
        keywords: ['background', 'backgrounds', 'svg', 'svg background', 'background svg', 'pattern', 'pattern background', 'abstract', 'abstract shapes', 'abstract background'],
    },
    {
        name: 'plain pattern',
        image: './public/assets/websiteimages/plainpattern.jpg',
        url: 'http://www.kennethcachia.com/plain-pattern/',
        description: 'Get creative: choose an SVG, or upload your own, and create a patterned background.',
        keywords: ['background', 'backgrounds', 'svg', 'svg background', 'background svg', 'pattern', 'pattern background'],
    },
    {
        name: 'patternico',
        image: './public/assets/websiteimages/patternico.jpg',
        url: 'https://patternico.com/',
        description: 'Choose from over 450 icons to create patterned backgrounds.',
        keywords: ['background', 'backgrounds', 'svg', 'svg background', 'background svg', 'pattern', 'pattern background'],
    },
    {
        name: 'pattern pad',
        image: './public/assets/websiteimages/patternpad.jpg',
        url: 'https://patternpad.com/editor.html',
        description: 'Choose from premade patterned backgrounds, and customize them to your liking.',
        keywords: ['background', 'backgrounds', 'svg', 'svg background', 'background svg', 'pattern', 'pattern background', 'abstract', 'abstract shapes', 'abstract background'],
    },
    {
        name: 'trianglify',
        image: './public/assets/websiteimages/trianglify.jpg',
        url: 'https://trianglify.io/',
        description: '($$$) Generate abstract triangle backgrounds either randomly or customly.',
        keywords: ['background', 'backgrounds', 'svg', 'svg background', 'background svg', 'pattern', 'pattern background', 'triangle', 'triangles', 'triangle background'],
    },
    {
        name: 'tabbied',
        image: './public/assets/websiteimages/tabbied.jpg',
        url: 'https://tabbied.com/select-artwork',
        description: 'Get started with 11 different pattern options, and then customize to your preferences.',
        keywords: ['background', 'backgrounds', 'svg', 'svg background', 'background svg', 'pattern', 'pattern background', 'abstract', 'abstract shapes', 'abstract background'],
    },
    {
        name: 'visiwig',
        image: './public/assets/websiteimages/tabbied.jpg',
        url: 'https://tabbied.com/select-artwork',
        description: 'A vector pattern generator for all your patterned background needs',
        keywords: ['background', 'backgrounds', 'svg', 'svg background', 'background svg', 'pattern', 'pattern background', 'abstract', 'abstract shapes', 'abstract background'],
    },
    {
        name: 'neumorphism.io',
        image: './public/assets/websiteimages/neumorphismio.jpg',
        url: 'https://neumorphism.io/#e0e0e0',
        description: 'Create neumorphic designs for your elements.',
        keywords: ['neumorphic', 'neumorphism', 'neumorphic shapes', 'minimal', 'modern', 'simple'],
    },
    {
        name: 'neumorphic.design',
        image: './public/assets/websiteimages/neumorphicdesign.jpg',
        url: 'https://neumorphic.design/',
        description: 'Customize neumorphic circles and squares.',
        keywords: ['neumorphic', 'neumorphism', 'neumorphic shapes', 'minimal', 'modern', 'simple'],
    },
    {
        name: 'glassui',
        image: './public/assets/websiteimages/glassui.jpg',
        url: 'https://ui.glass/generator/',
        description: 'Design and customize glassmorphic elements.',
        keywords: ['glassmorphism', 'glass', 'glassmorphic', 'glass effect', 'glass-effect', 'frosted glass', 'minimal', 'modern', 'simple'],
    },
    {
        name: 'glassmorphism generator',
        image: './public/assets/websiteimages/glassmorphism.jpg',
        url: 'https://hype4.academy/tools/glassmorphism-generator',
        description: 'Design and customize glassmorphic elements.',
        keywords: ['glassmorphism', 'glass', 'glassmorphic', 'glass effect', 'glass-effect', 'frosted glass', 'minimal', 'modern', 'simple'],
    },
    {
        name: 'fontjoy',
        image: './public/assets/websiteimages/fontjoy.jpg',
        url: 'https://fontjoy.com/',
        description: 'Generate beautiful font pairings with the click of a button.',
        keywords: ['font', 'fonts', 'font generator', 'typography'],
    },
    {
        name: 'box shadow generator',
        image: './public/assets/websiteimages/shadows.jpg',
        url: 'https://shadows.brumm.af/',
        description: 'An incredibly sophisticated box shadow generator offering full customization, down to the pixel.',
        keywords: ['box shadow', 'shadow', 'shadows', 'element shadow'],
    },
    {
        name: 'box shadow examples',
        image: './public/assets/websiteimages/boxshadowexamples.jpg',
        url: 'https://getcssscan.com/css-box-shadow-examples',
        description: 'Choose pre-generated box shadows with just one click.',
        keywords: ['box shadow', 'box', 'shadow', 'shadows', 'element shadow'],
    },
    {
        name: 'text shadow generator',
        image: './public/assets/websiteimages/textshadow.jpg',
        url: 'https://cssbud.com/css-generator/css-text-shadow-generator/',
        description: 'Customize and generate text shadows.',
        keywords: ['text shadow', 'shadow', 'shadows', 'element shadow', 'text', 'text effects', 'text effect'],
    },
    {
        name: 'text glow generator',
        image: './public/assets/websiteimages/textglow.jpg',
        url: 'https://cssbud.com/css-generator/css-text-glow-generator/',
        description: 'Customize and generate glowing texts.',
        keywords: ['text glow', 'glow', 'glowing', 'text', 'text effects', 'text effect'],
    },
    {
        name: 'glow generator',
        image: './public/assets/websiteimages/glowgenerator.jpg',
        url: 'https://cssbud.com/css-generator/css-glow-generator/',
        description: 'Customize and generate glowing elements.',
        keywords: ['box glow', 'glow', 'glowing', 'box', 'element glow', 'element effect'],
    },
    {
        name: 'text underline generator',
        image: './public/assets/websiteimages/textunderline.jpg',
        url: 'https://cssbud.com/css-generator/css-underline-generator/',
        description: 'Underlining is fully customizable! And its made easy when using this underline generator.',
        keywords: ['text underline', 'underline', 'text', 'text effects', 'text effect'],
    },
    {
        name: 'hamburger menu animations',
        image: './public/assets/websiteimages/hamburgeranimations.jpg',
        url: 'https://jonsuh.com/hamburgers/',
        description: 'Find cool animations for your hamburger menu!',
        keywords: ['animations', 'animated', 'animation', 'hamburger', 'hamburger menu', 'hamburger animation', 'menu animation'],
    },
    {
        name: 'favicon maker',
        image: './public/assets/websiteimages/faviconmaker.jpg',
        url: 'https://formito.com/tools/favicon',
        description: 'Create your very own custom favicon.',
        keywords: ['favicon'],
    },
]